### ISSUE TITLE
doesn't save files correctly

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/grunt-handlebars-layout#3]
not appending filename to directory

`Warning: Unable to write "dist/" file (Error code: EISDIR). Use --force to continue.`

config:

```
handlebars_layout:
  options:
    basePath: '<%= dev %>'
    partials:
      - '<%= dev %>/layouts/**/*.html'
      - '<%= dev %>/modules/**/*.html'
    data:
      - '<%= dev %>/data/**/*.yaml'
  files:
    '<%= dist %>/' : '<%= dev %>/*.html'
```

**Comment by jgallen23** [comment]
I think I might have fixed by changing config to:

```
handlebars_layout:
  options:
    basePath: '<%= dev %>'
    partials:
      - '<%= dev %>/layouts/**/*.html'
      - '<%= dev %>/modules/**/*.html'
    data:
      - '<%= dev %>/data/**/*.yaml'
  files:
    -
      expand: true
      cwd: '<%= dev %>'
      src: '**/*.html'
      dest: '<%= dist %>'
```
